### ISSUE TITLE
Not working with > 10 mins video

### ISSUE THREAD

**Issue by a0ali0taha** [karim-bouchez/moubah#9]
Salam 
I tried more than 10 minutes video, unfortunately, it is not working
please check attached logs
[main-process.log](https://github.com/itkho/moubah/files/15138049/main-process.log)

**Comment by karim-bouchez** [comment]
Wa 3alayka as salam

Just to be sure, you have the last version? 

And, I will check in cha Allah, but I'm almost sure that this is because of the arabic letters in the title

**Comment by karim-bouchez** [comment]
In the title, I see "... with > 10 mins video"
Is it really just for video of 10+ minutes ?

**Comment by AhmedTaha-Tamkeen** [comment]
I checked short videos less than 10 min and it works, more is not working 
check the logs please

**Comment by karimelhajoui63** [comment]
@a0ali0taha I tried the exact same video, and it worked.
What is your OS ? 

To be sure it's about the video length (and not the video title), try with theses three videos please, and tell me which one work:
- https://youtu.be/42AVhDZJcNg?si=vKCDHqJu37uqjucs (with a `'` in the title) <-- I really think that the problem is here
- https://youtu.be/JWt5_NJuhME?si=JcaH6XnXqcbZitLb (more than 10min)
- https://youtu.be/RU7yFzuYl6g?si=boU6pu6mhopI6E-- (arabic letters in title)

**Comment by karim-bouchez** [comment]
@a0ali0taha I tried the exact same video, and it worked.
What is your OS ? 

To be sure it's about the video length (and not the video title), try with theses three videos please, and tell me which one work:
- https://youtu.be/42AVhDZJcNg?si=vKCDHqJu37uqjucs (with a `'` in the title) <-- I really think that the problem is here
- https://youtu.be/JWt5_NJuhME?si=JcaH6XnXqcbZitLb (more than 10min)
- https://youtu.be/RU7yFzuYl6g?si=boU6pu6mhopI6E-- (arabic letters in title)

**Comment by a0ali0taha** [comment]
Only this https://www.youtube.com/watch?v=RU7yFzuYl6g is working


this one has a problem https://www.youtube.com/watch?v=JWt5_NJuhME
check its logs
`[14:03:44.100] DEBUG: child process FFmpeg addAudioToVideo exited with code 1
[14:03:44.100] ERROR: ENOENT: no such file or directory, copyfile 'C:\Users\User\AppData\Local\Temp\Moubah\video.mp4' -> 'C:\Users\User\Videos\Moubah\Best Quran recitation to The Prophet Moses and Pharaoh story by Raad alkurdi - JWt5_NJuhME\video.mp4'
    err: {
      "type": "Error",
      "message": "ENOENT: no such file or directory, copyfile 'C:\\Users\\User\\AppData\\Local\\Temp\\Moubah\\video.mp4' -> 'C:\\Users\\User\\Videos\\Moubah\\Best Quran recitation to The Prophet Moses and Pharaoh story by Raad alkurdi - JWt5_NJuhME\\video.mp4'",
      "stack":
          Error: ENOENT: no such file or directory, copyfile 'C:\Users\User\AppData\Local\Temp\Moubah\video.mp4' -> 'C:\Users\User\Videos\Moubah\Best Quran recitation to The Prophet Moses and Pharaoh story by Raad alkurdi - JWt5_NJuhME\video.mp4'
              at Object.copyFileSync (node:fs:2800:3)
              at Object.func [as copyFileSync] (node:electron/js2c/asar_bundle:5:1812)
              at ChildProcess.<anonymous> (C:\Users\User\AppData\Local\Programs\moubah\resources\app\main\out\lib\ffmpeg.js:124:26)
              at ChildProcess.emit (node:events:402:35)
              at maybeClose (node:internal/child_process:1064:16)
              at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
      "errno": -4058,
      "syscall": "copyfile",
      "code": "ENOENT",
      "path": "C:\\Users\\User\\AppData\\Local\\Temp\\Moubah\\video.mp4",
      "dest": "C:\\Users\\User\\Videos\\Moubah\\Best Quran recitation to The Prophet Moses and Pharaoh story by Raad alkurdi - JWt5_NJuhME\\video.mp4"
    }
`
this file is not exist C:\\Users\\User\\AppData\\Local\\Temp\\Moubah\\video.mp4

this one has issue as well
`[14:08:09.054] ERROR: ENOENT: no such file or directory, copyfile 'C:\Users\User\AppData\Local\Temp\Moubah\video.mp4' -> 'C:\Users\User\Videos\Moubah\Mevlan Kurtishi - 25 Duas from Qur'an  مولانا - دعاء من القرآن - 42AVhDZJcNg\video.mp4'
    err: {
      "type": "Error",
      "message": "ENOENT: no such file or directory, copyfile 'C:\\Users\\User\\AppData\\Local\\Temp\\Moubah\\video.mp4' -> 'C:\\Users\\User\\Videos\\Moubah\\Mevlan Kurtishi - 25 Duas from Qur'an  مولانا - دعاء من القرآن - 42AVhDZJcNg\\video.mp4'",
      "stack":
          Error: ENOENT: no such file or directory, copyfile 'C:\Users\User\AppData\Local\Temp\Moubah\video.mp4' -> 'C:\Users\User\Videos\Moubah\Mevlan Kurtishi - 25 Duas from Qur'an  مولانا - دعاء من القرآن - 42AVhDZJcNg\video.mp4'
              at Object.copyFileSync (node:fs:2800:3)
              at Object.func [as copyFileSync] (node:electron/js2c/asar_bundle:5:1812)
              at ChildProcess.<anonymous> (C:\Users\User\AppData\Local\Programs\moubah\resources\app\main\out\lib\ffmpeg.js:124:26)
              at ChildProcess.emit (node:events:402:35)
              at maybeClose (node:internal/child_process:1064:16)
              at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
      "errno": -4058,
      "syscall": "copyfile",
      "code": "ENOENT",
      "path": "C:\\Users\\User\\AppData\\Local\\Temp\\Moubah\\video.mp4",
      "dest": "C:\\Users\\User\\Videos\\Moubah\\Mevlan Kurtishi - 25 Duas from Qur'an  مولانا - دعاء من القرآن - 42AVhDZJcNg\\video.mp4"
    }`


my thoughts it is not Arabic , maybe number of chunks

**Comment by karim-bouchez** [comment]
Can you provide me the full log file for `JWt5_NJuhME` please @a0ali0taha ?
I may work on this this week-end in cha Allah

**Comment by a0ali0taha** [comment]
Salam @karim-bouchez 
Sorry for being late, I was trying to investigate the issue, 
I found that ' single quotation is a problem thus when it is inserted in audioListFile.txt it cannot be handled by ffmpeg because the line inserted for chunks like below
`file 'C:\Users\User\Videos\Moubah\قصص الآيات في القرآن  الحلقة 1  حاطب بن أبي بلتعة - ج 1  Verses Stories from Qur'an - lttUGHte4mY\chunks\done\chunk_000.wav'`
need to remove ' if exist, I do not know where to add
